site_name: Source++ Docs
theme:
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  logo: assets/logo.svg
  favicon: assets/logo.svg
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigation.top
    - toc.integrate
#    - navigation.sections

plugins:
  - search
  - awesome-pages
  - macros
  - git-revision-date-localized

extra_css:
  - stylesheets/extra.css
  - stylesheets/jquery.fancybox.min.css

extra_js:
  - assets/extra.js

extra_javascript:
  - https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js

extra:
  homepage: https://sourceplus.plus
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/sourceplusplus
    - icon: fontawesome/brands/github
      link: https://github.com/sourceplusplus
  analytics:
    provider: google
    property: UA-111677030-1
  spp:
    latest_version: 0.5.4 #todo: could pull from changelog

markdown_extensions:
  - attr_list
  - fancyboxmd:
      preview_width: "1000"
  - admonition
  - pymdownx.details
  - toc:
      permalink: ⚓︎
      toc_depth: 3
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
  - pymdownx.keys

copyright: © 2022 | CodeBrig, Inc. | All Rights Reserved.

repo_url: https://github.com/sourceplusplus/interface-jetbrains
edit_uri: https://github.com/sourceplusplus/documentation/tree/master/docs/
